/**
 * Autogenerated local (chainId 31337) overlay — do not edit by hand.
 *
 * This file is gitignored: your local deployment addresses live here and
 * should not be committed. Run `pnpm generate` after `pnpm deploy:localhost`
 * to refresh, or after a fresh clone to materialize a stub.
 */
import type { ContractDeployment } from "~~/utils/contract";

export const CipherProtocol = {
  31337: {
    address: "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0",
    abi: [
      {
        type: "receive",
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "BORROW_FEE_BPS",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "BPS_DENOMINATOR",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "INTEREST_BPS",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "LOAN_DURATION",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "TIER_A_LIMIT",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "TIER_A_THRESHOLD",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "TIER_B_LIMIT",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "TIER_B_THRESHOLD",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "TIER_C_LIMIT",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "TIER_C_THRESHOLD",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "TIER_D_LIMIT",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "TIER_D_THRESHOLD",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "applyForScore",
        inputs: [
          {
            name: "extTxCount",
            type: "bytes32",
            internalType: "externalEuint32",
          },
          {
            name: "extTotalVolume",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "extWalletAgeDays",
            type: "bytes32",
            internalType: "externalEuint32",
          },
          {
            name: "proofTx",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "proofVol",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "proofAge",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "borrow",
        inputs: [
          {
            name: "amount",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "defaultCount",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "depositLiquidity",
        inputs: [],
        outputs: [],
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "deposits",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "encryptedScores",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "encryptedTiers",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getDefaultCount",
        inputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEncryptedScore",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEncryptedTier",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getLoanInfo",
        inputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "tuple",
            internalType: "struct CipherProtocol.Loan",
            components: [
              {
                name: "principal",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "repaid",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "active",
                type: "bool",
                internalType: "bool",
              },
              {
                name: "startTime",
                type: "uint256",
                internalType: "uint256",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getPoolBalance",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getRepaymentDue",
        inputs: [
          {
            name: "borrower",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "totalDue",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "remaining",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getTierLimit",
        inputs: [
          {
            name: "tier",
            type: "uint8",
            internalType: "uint8",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "getTotalAssets",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getUserDepositValue",
        inputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getUtilization",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "liquidate",
        inputs: [
          {
            name: "borrower",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "loans",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "principal",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "repaid",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "active",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "startTime",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "repayLoan",
        inputs: [],
        outputs: [],
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "revealTier",
        inputs: [
          {
            name: "tier",
            type: "uint8",
            internalType: "uint8",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "totalBorrows",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalDeposits",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "userTier",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint8",
            internalType: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "withdrawLiquidity",
        inputs: [
          {
            name: "amount",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "DefaultRecorded",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "newDefaultCount",
            type: "uint32",
            indexed: false,
            internalType: "uint32",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "LiquidityDeposited",
        inputs: [
          {
            name: "lender",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "amount",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "LiquidityWithdrawn",
        inputs: [
          {
            name: "lender",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "amount",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "LoanRepaid",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "amount",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "LoanTaken",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "principal",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
          {
            name: "fee",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
          {
            name: "received",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "ScoreApplied",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "scoreHandle",
            type: "bytes32",
            indexed: false,
            internalType: "bytes32",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "TierRevealed",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "tier",
            type: "uint8",
            indexed: false,
            internalType: "uint8",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 13,
  },
} as const satisfies Partial<Record<number, ContractDeployment>>;
